-- MySQL Script generated by MySQL Workbench
-- Wed Jun  9 11:51:24 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema employee_tracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `employee_tracker` ;

-- -----------------------------------------------------
-- Schema employee_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employee_tracker` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employee_tracker` ;

-- -----------------------------------------------------
-- Table `employee_tracker`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee_tracker`.`department` ;

CREATE TABLE IF NOT EXISTS `employee_tracker`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee_tracker`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee_tracker`.`role` ;

CREATE TABLE IF NOT EXISTS `employee_tracker`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NULL DEFAULT NULL,
  `salary` VARCHAR(45) NULL DEFAULT NULL,
  `department_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `employee_tracker`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee_tracker`.`employee` ;

CREATE TABLE IF NOT EXISTS `employee_tracker`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NULL DEFAULT NULL,
  `last_name` VARCHAR(30) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `manager_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_manager_id_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_manager_id`
    FOREIGN KEY (`manager_id`)
    REFERENCES `employee_tracker`.`employee` (`id`),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `employee_tracker`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
